name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - run: make test

      - run: make format

      - uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: make build
