name: Deploy
on:
  push:
    branches:
      - master

env:
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
  RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
  RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  SNS_EMAIL: ${{ secrets.SNS_EMAIL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm install -g serverless

    - run: npm install

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Deploy
      run: make deploy
