name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - run: make install

      - run: make test

      - run: make format

      - uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""
        with:
          args: "run"

      - run: make build

      - run: make deploy
